apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test-kognic
  namespace: kargo-demo
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-kognic
      sources:
        direct: true
  promotionTemplate:
    spec:
      vars:
        - name: gitopsRepo
          value: ${GITOPS_REPO_URL}
        - name: imageRepo
          value: public.ecr.aws/nginx/nginx
        - name: srcPath
          value: ./src
        - name: outPath
          value: ./out
      steps:
        - uses: git-clone
          config:
            repoURL: \${{ vars.gitopsRepo }}
            checkout:
              - branch: main
                path: \${{ vars.srcPath }}
              - branch: stage/\${{ ctx.stage }}
                create: true
                path: \${{ vars.outPath }}
        - uses: git-clear
          config:
            path: \${{ vars.outPath }}
        - uses: kustomize-set-image
          as: update-image
          config:
            path: \${{ vars.srcPath }}/base
            images:
              - image: \${{ vars.imageRepo }}
                tag: \${{ imageFrom(vars.imageRepo).Tag }}
        - uses: kustomize-build
          config:
            path: \${{ vars.srcPath }}/stages/\${{ ctx.stage }}
            outPath: \${{ vars.outPath }}/manifests.yaml
        - uses: git-commit
          as: commit
          config:
            path: \${{ vars.outPath }}
            messageFromSteps:
              - update-image
        - uses: git-push
          config:
            path: \${{ vars.outPath }}
        - uses: argocd-update
          config:
            apps:
              - name: kargo-kognic-\${{ ctx.stage }}
                sources:
                  - repoURL: \${{ vars.gitopsRepo }}
                    desiredRevision: \${{ outputs.commit.commit }}
