apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-kognic
spec:
  promotionTemplate:
    spec:
      steps:
        - config:
            checkout:
              - branch: main
                path: ${{ vars.srcPath }}
              - branch: stage-kognic/${{ ctx.stage }}
                create: true
                path: ${{ vars.outPath }}
            repoURL: ${{ vars.gitopsRepo }}
          uses: git-clone
        - config:
            path: ${{ vars.outPath }}
          uses: git-clear
        - as: copy
          uses: copy
          config:
            inPath: ${{ vars.srcPath }}
            outPath: ${{ vars.outPath }}
        - as: update-image
          config:
            images:
              - image: ${{ vars.imageRepo }}
                tag: ${{ imageFrom(vars.imageRepo).Tag }}
            path: ${{ vars.outPath }}/stages-kognic/${{ ctx.stage }}
          uses: kustomize-set-image
        - as: commit
          config:
            messageFromSteps:
              - update-image
            path: ${{ vars.outPath }}
          uses: git-commit
        - as: push
          config:
            path: ${{ vars.outPath }}
            generateTargetBranch: true
          uses: git-push
        - as: open-pr
          config:
            repoURL: ${{ vars.gitopsRepo }}
            provider: github
            sourceBranch: ${{ outputs.push.branch }}
            targetBranch: stage-kognic/${{ ctx.stage }}
            createTargetBranch: true
          uses: git-open-pr
        - as: wait-for-pr
          config:
            repoURL: ${{ vars.gitopsRepo }}
            prNumber: ${{ outputs['open-pr'].prNumber }}
          uses: git-wait-for-pr
        - config:
            apps:
              - name: kargo-kognic-${{ ctx.stage }}
                sources:
                  - desiredRevision: ${{ outputs.commit.commit }}
                    repoURL: ${{ vars.gitopsRepo }}
          uses: argocd-update
      vars:
        - name: gitopsRepo
          value: https://github.com/NissesSenap/kargo-demo.git
        - name: imageRepo
          value: public.ecr.aws/nginx/nginx
        - name: srcPath
          value: ./src
        - name: outPath
          value: ./out
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-kognic
      sources:
        direct: true
