apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-kognic
spec:
  promotionTemplate:
    spec:
      steps:
        - config:
            checkout:
              - branch: main
                path: ${{ vars.srcPath }}
            repoURL: ${{ vars.gitopsRepo }}
          uses: git-clone
        - as: update-image
          config:
            images:
              - image: ${{ vars.imageRepo }}
                tag: ${{ imageFrom(vars.imageRepo).Tag }}
            path: ${{ vars.srcPath }}/stages-kognic/${{ ctx.stage }}
          uses: kustomize-set-image
        - as: commit
          config:
            messageFromSteps:
              - update-image
            path: ${{ vars.srcPath }}
          uses: git-commit
        - as: push
          config:
            path: ${{ vars.srcPath }}
            generateTargetBranch: true
          uses: git-push
        - as: open-pr
          config:
            repoURL: ${{ vars.gitopsRepo }}
            provider: github
            sourceBranch: ${{ outputs.push.branch }}
            targetBranch: main
            createTargetBranch: true
          uses: git-open-pr
        - as: wait-for-pr
          config:
            repoURL: ${{ vars.gitopsRepo }}
            prNumber: ${{ outputs['open-pr'].prNumber }}
          uses: git-wait-for-pr
      vars:
        - name: gitopsRepo
          value: https://github.com/NissesSenap/kargo-demo.git
        - name: imageRepo
          value: public.ecr.aws/nginx/nginx
        - name: srcPath
          value: ./src
        - name: outPath
          value: ./out
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-kognic
      sources:
        direct: true
