apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-kognic
spec:
  promotionTemplate:
    spec:
      vars:
        - name: gitRepo
          value: https://github.com/NissesSenap/kargo-demo.git
        - name: srcPath
          value: ./src
        - name: imageRepo
          value: public.ecr.aws/nginx/nginx
      steps:
        - uses: git-clone
          config:
            repoURL: ${{ vars.gitRepo }}
            checkout:
              - branch: main
                path: ${{ vars.srcPath }}
        - uses: yaml-update
          as: update-image
          config:
            path: ${{ vars.srcPath }}/stages-kognic/${{ ctx.stage }}/values.yaml
            updates:
              - key: grafana-operator.image.tag
                value: ${{ imageFrom(vars.imageRepo).Tag }}
              - key: grafana-operator.image.repository
                value: ${{ vars.imageRepo }}
        - uses: git-commit
          as: commit
          config:
            path: ${{ vars.srcPath }}
            messageFromSteps:
              - update-image
        - as: push
          uses: git-push
          config:
            path: ${{ vars.srcPath }}
            generateTargetBranch: true
        - as: open-pr
          config:
            repoURL: ${{ vars.gitRepo }}
            provider: github
            sourceBranch: ${{ outputs.push.branch }}
            targetBranch: main
            createTargetBranch: true
          uses: git-open-pr
        - as: wait-for-pr
          config:
            repoURL: ${{ vars.gitRepo }}
            prNumber: ${{ outputs['open-pr'].prNumber }}
          uses: git-wait-for-pr
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-kognic
      sources:
        direct: true
